--- git/Makefile	2017-04-29 09:15:34.974520121 +0200
+++ git/Makefile	2017-04-29 09:09:29.861008323 +0200
@@ -96,7 +96,7 @@
 
 ARCH ?= $(SUBARCH)
 CROSS_COMPILE ?=
-KVER  := $(shell uname -r)
+KVER  ?= $(shell uname -r)
 KSRC ?= /lib/modules/$(KVER)/build
 MODDESTDIR := /lib/modules/$(KVER)/kernel/drivers/net/wireless
 INSTALL_PREFIX :=
@@ -149,14 +149,14 @@
 	$(CROSS_COMPILE)strip 8188eu.ko --strip-unneeded
 
 install:
-	install -p -D -m 644 8188eu.ko  $(MODDESTDIR)/8188eu.ko
-	/sbin/depmod -a ${KVER}
-	mkdir -p /lib/firmware/rtlwifi
-	cp -n rtl8188eufw.bin /lib/firmware/rtlwifi/.
+	install -p -D -m 644 8188eu.ko  $(INSTALL_PREFIX)$(MODDESTDIR)/8188eu.ko
+#	/sbin/depmod -a ${KVER}
+#	install -d $(INSTALL_PREFIX)/lib/firmware/rtlwifi/
+#	install -m 755 rtl8188eufw.bin $(INSTALL_PREFIX)/lib/firmware/rtlwifi/
 
 uninstall:
-	rm -f $(MODDESTDIR)/8188eu.ko
-	/sbin/depmod -a ${KVER}
+	rm -f $(PREFIX_INSTALL)$(MODDESTDIR)/8188eu.ko
+#	/sbin/depmod -a ${KVER}
 
 config_r:
 	@echo "make config"
